[package]
name = "rust_logger"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[features]
ffi-test=[]
[lib]
crate-type=["staticlib","rlib"]
[dependencies]
cxx.workspace = true

[build-dependencies]
cxx-build.workspace = true

