dist: xenial
sudo: required

language: cpp

git:
  depth: false

branches:
  only:
  - staging
  - trying
  - master

addons:
  snaps:
  - lxd

env:
  global:
  - SNAPCRAFT_ENABLE_ERROR_REPORTING=0
  - SNAPCRAFT_BUILD_ENVIRONMENT=lxd

install:
- sudo apt remove --assume-yes lxd
- sudo /snap/bin/lxd waitready
- sudo /snap/bin/lxd init --auto
- sudo adduser $USER lxd

before_script:
- "[ ! -f tests/travis-${BUILD_TYPE}.patch ] || patch -p1 < tests/travis-${BUILD_TYPE}.patch"
- |
  sg lxd -c "/snap/bin/lxc launch ubuntu:18.04 snapcraft-multipass --config user.user-data='#cloud-config
package_update: true' --config raw.idmap='uid $( id -u ) 0
gid $( id -g ) 0'"
- sg lxd -c "/snap/bin/lxc config device add snapcraft-multipass project disk path=/root/project source=$PWD"
- while ! sg lxd -c '/snap/bin/lxc exec snapcraft-multipass -- cloud-init status' | grep 'done'; do sleep 5; done
- while ! sg lxd -c '/snap/bin/lxc exec snapcraft-multipass -- snap install snapcraft --classic'; do sleep 5; done

after_failure:
- cat /tmp/*/trace.txt

jobs:
  include:
    - env: BUILD_TYPE=RelWithDebInfo
      script:
      - sg lxd -c '/snap/bin/lxc exec snapcraft-multipass -- sh -c "cd project; snapcraft --destructive-mode"'

    - env: BUILD_TYPE=Debug
      script:
      - sg lxd -c '/snap/bin/lxc exec snapcraft-multipass -- sh -c "cd project; snapcraft build --destructive-mode multipass"'
      - sg lxd -c
          '/snap/bin/lxc exec snapcraft-multipass --
             env CTEST_OUTPUT_ON_FAILURE=1
                 LD_LIBRARY_PATH=/root/project/stage/usr/lib/x86_64-linux-gnu/:/root/project/stage/lib/
                 /root/project/parts/multipass/build/bin/multipass_tests'

    - env: BUILD_TYPE=Coverage
      script:
      - sg lxd -c '/snap/bin/lxc exec snapcraft-multipass -- sh -c "cd project; snapcraft build --destructive-mode multipass"'
      - sg lxd -c
          '/snap/bin/lxc exec snapcraft-multipass --
             env CTEST_OUTPUT_ON_FAILURE=1
                 LD_LIBRARY_PATH=/root/project/stage/usr/lib/x86_64-linux-gnu/:/root/project/stage/lib/
                 cmake --build /root/project/parts/multipass/build --target covreport'
      after_success:
      - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
    - if: (type = pull_request AND head_repo = CanonicalLtd/multipass)
          OR (type != pull_request AND repo = CanonicalLtd/multipass)
      env: BUILD_TYPE=macOS
      git:
        submodules: false
      sudo: false
      before_install:
      - openssl aes-256-cbc -K $encrypted_8d49841daf21_key -iv $encrypted_8d49841daf21_iv
        -in tools/bot-data.tar.xz.enc -out tools/bot-data.tar.xz -d
      - tar --extract --xz --file tools/bot-data.tar.xz --directory ${HOME}
      install: ~
      before_script: ~
      script:
      - |
        if [ "${TRAVIS_EVENT_TYPE}" == "pull_request" ]; then
          REF="+refs/pull/${TRAVIS_PULL_REQUEST}/merge"
        else
          REF="${TRAVIS_COMMIT}"
        fi
        ssh -q -p ${MAC_PORT} ${MAC_USERHOST} multipass-build/build-in-snapshot.sh "${REF}"
      after_failure: ~
