name: multipass_gui
description: A new Flutter project.
publish_to: 'none'

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  async: ^2.13.0
  basics: ^0.10.0
  built_collection: ^5.1.1
  collection: ^1.19.1
  dartssh2:
    git:
      url: https://github.com/canonical/dartssh2.git
      ref: 2.12.0+mp
  extended_text: ^15.0.0
  ffi: ^2.1.4
  file_selector: ^1.0.3
  fl_chart: ^1.1.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.1
  flutter_svg: ^2.0.17
  fpdart: ^1.1.1
  grpc: ^5.0.0
  hotkey_manager: ^0.2.3
  intersperse: ^2.0.0
  intl: ^0.20.2
  local_notifier: ^0.1.6
  logger: ^2.5.0
  path_provider: ^2.1.5
  protobuf: 6.0.0
  rxdart: ^0.28.0
  shared_preferences: ^2.5.2
  synchronized: ^3.3.1
  tray_menu:
    git:
      url: https://github.com/canonical/tray_menu.git
      ref: main
  two_dimensional_scrollables: ^0.3.3
  url_launcher: ^6.3.1
  win32: 6.0.0
  window_manager: ^0.5.0
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
      ref: 6c66ad2
  xterm:
    git:
      url: https://github.com/levkropp/xterm.dart
      ref: 4.0.0+mp

dependency_overrides:
  hotkey_manager_linux:
    git:
      url: https://github.com/canonical/hotkey_manager.git
      ref: no-cooked-accel
      path: packages/hotkey_manager_linux
  vector_math: ^2.2.0

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/Ubuntu-R.ttf
        - asset: assets/Ubuntu-B.ttf
          weight: 700
        - asset: assets/Ubuntu-L.ttf
          weight: 300
    - family: UbuntuMono
      fonts:
        - asset: assets/UbuntuMono-R.ttf
        - asset: assets/UbuntuMono-B.ttf
          weight: 700
    - family: NotoColorEmoji
      fonts:
        - asset: assets/NotoColorEmoji-Regular.ttf
    - family: FreeSans
      fonts:
        - asset: assets/FreeSans.ttf
