name: multipass_gui
description: A new Flutter project.
publish_to: 'none'

version: 1.14.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  async: ^2.11.0
  basics: ^0.10.0
  built_collection: ^5.1.1
  collection: ^1.18.0
  dartssh2:
    git:
      url: https://github.com/andrei-toterman/dartssh2.git
      ref: use-raw-socket
  ffi: ^2.1.0
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  flutter_svg: ^2.0.10+1
  fpdart: ^1.1.0
  grpc: ^3.2.4
  hotkey_manager: ^0.2.3
  intl: ^0.19.0
  logger: ^2.3.0
  path_provider: ^2.1.3
  protobuf: ^3.1.0
  rxdart: ^0.28.0
  shared_preferences: ^2.2.3
  synchronized: ^3.1.0+1
  tray_menu:
    git:
      url: https://github.com/andrei-toterman/tray_menu.git
      ref: 7c1394c
  two_dimensional_scrollables: ^0.2.1
  url_launcher: ^6.3.0
  win32: ^5.2.0
  window_manager: ^0.3.9
  xterm: ^3.6.0

dependency_overrides:
  hotkey_manager_linux:
    git:
      url: https://github.com/andrei-toterman/hotkey_manager.git
      ref: no-cooked-accel
      path: packages/hotkey_manager_linux

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/Ubuntu-R.ttf
        - asset: assets/Ubuntu-B.ttf
          weight: 700
        - asset: assets/Ubuntu-L.ttf
          weight: 300
