#
name: Automatic doc checks

on:
  workflow_call:
  workflow_dispatch:
    # Manual trigger

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  documentation-checks:
    runs-on: ubuntu-latest
    steps:
      - name: â€œIntentionally fail for testingâ€
        run: |
          echo "ğŸš¨ Forcing failure (docs workflow) for testing purposes"
          exit 1
