name: Snaps

on:
  schedule:
  - cron: '0 5 * * *'

jobs:
  ProcessUSNs:
    if: ${{ github.repository == 'canonical/multipass' }}

    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Python dependencies
      uses: BSFishy/pip-action@v1
      with:
        requirements: tools/requirements.txt

    - name: Install Snap dependencies
      run: |
        sudo snap install review-tools

    - name: Set up Launchpad credentials
      uses: DamianReeves/write-file-action@v1.3
      with:
        path: lp_credentials
        contents: ${{ secrets.LAUNCHPAD_CREDENTIALS }}

    - name: Check for USNs
      run: tools/process_snaps.py lp_credentials
