name: Test hooks
on:
  workflow_call:
  workflow_dispatch: # Manual trigger

jobs:
  TestHooks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'

      - name: Install Python dependencies
        uses: BSFishy/pip-action@v1
        with:
          requirements: git-hooks/requirements.txt

      - name: Run hook tests
        run: |
          for hook in git-hooks/*.py; do
            echo "Testing $hookâ€¦"
            "$hook" --tests
          done
